In [114]:
class NeuralNetwork:
    def __init__(self, x, y, lr):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4)
        self.biases1    = np.random.rand(1)
        self.weights2   = np.random.rand(4,1)    
        self.biases2    = np.random.rand(1)
        self.y          = y
        self.output     = np.zeros(self.y.shape)
        self.lr         = lr
        
    
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoid_derivative(self,z):
        #Gradient of sigmoid
        #return np.exp(-z)/((1+np.exp(-z))**2)
        return z * (1.0 - z)
        
        
    def feedforward(self):
        self.z2 = np.dot(self.input, self.weights1) + self.biases1
        self.z3 = np.dot(self.sigmoid(self.z2), self.weights2) + self.biases2
        self.output = self.sigmoid(self.z3)
        
        
    def backward(self):
        d_weights2 = np.dot(self.sigmoid(self.z2).T, (2*(self.y - self.output) * self.sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * self.sigmoid_derivative(self.output), self.weights2.T) * self.sigmoid_derivative(self.sigmoid(self.z2))))
        d_biases2 = 2*(self.y - self.output) * self.sigmoid_derivative(self.output)
        d_biases1 = np.dot(2*(self.y - self.output) * self.sigmoid_derivative(self.output), self.weights2.T) * self.sigmoid_derivative(self.sigmoid(self.z2))
        #print(self.weights2, self.weights1)
        
        self.weights1 += self.lr * d_weights1
        self.weights2 += self.lr * d_weights2
        
        #print("after") 
        #print(self.weights2, self.weights1)
        #print(d_biases2.shape, d_biases1.shape)
        self.biases1 = self.biases1 + self.lr * d_biases1
        self.biases2 = self.biases2 + self.lr * d_biases2
        
        
        
        

In [4]:
import numpy as np
np.random.rand(4,1)

array([[0.1696738 ],
       [0.39847618],
       [0.69828306],
       [0.9797259 ]])

In [27]:
np.random.rand(1,1)

array([[0.07002214]])

In [12]:
def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
def sigmoidPrime(self,z):
    #Gradient of sigmoid
    return np.exp(-z)/((1+np.exp(-z))**2)

In [ ]:
def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

In [86]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(1500):
        nn.feedforward()
        nn.backprop()

    print(nn.output)


[[0.02423679]
 [0.9769097 ]
 [0.9780617 ]
 [0.02415337]]


In [11]:
import numpy as np

# sigmoid function to normalize inputs
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# sigmoid derivatives to adjust synaptic weights
def sigmoid_derivative(x):
    return x * (1 - x)

# input dataset
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

# output dataset
training_outputs = np.array([[0,1,1,0]]).T

# seed random numbers to make calculation
np.random.seed(1)

# initialize weights randomly with mean 0 to create weight matrix, synaptic weights
synaptic_weights = 2 * np.random.random((3,1)) - 1

print('Random starting synaptic weights: ')
print(synaptic_weights)

# Iterate 10,000 times
for iteration in range(10000):

    # Define input layer
    input_layer = training_inputs
    # Normalize the product of the input layer with the synaptic weights
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))

    # how much did we miss?
    error = training_outputs - outputs

    # multiply how much we missed by the
    # slope of the sigmoid at the values in outputs
    adjustments = error * sigmoid_derivative(outputs)

    # update weights
    synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training: ')
print(synaptic_weights)

print("Output After Training:")
print(outputs)

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Output After Training:
[[0.00966449]
 [0.99211957]
 [0.99358898]
 [0.00786506]]


In [126]:
X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
y = np.array([[0],[1],[1],[0]])
nn = NeuralNetwork(X,y,.01)

for i in range(80000):
    nn.feedforward()
    nn.backward()

print(nn.output)

[[0.01782286]
 [0.98182786]
 [0.98183764]
 [0.01816635]]
